### ISSUE TITLE
Keine Werte angezeigt

### ISSUE THREAD

**Issue by Sledgehammer101** [klein0r/ioBroker.youtube#14]
Nach der Installation werden in den Objekten keine Werte angezeigt. Der API Key liefert Daten, da ich sie über Lametric nutze. 

Neustart des Adapter und Änderung des Chron Jobs bringt keine Änderung. 

Habe auch schon deinstalliert, wieder installiert und bin alle Möglichkeiten soweit durchgegangen. Es werden weiterhin keine Werte angezeigt.

**Comment by klein0r** [comment]
Was steht denn im Log? Bitte mal auf Debug stellen und alles hier posten

**Comment by Sledgehammer101** [comment]
Diese Meldung bekomme ich im Log nach einem Neustart: 


youtube.0 | 2020-05-20 19:43:02.593 | error | (10150) youtube/v3/search - Status Code: 403 / Content: {"error":{"errors":[{"domain":"usageLimits","reason":"accessNotConfigured","message":"Access Not Configured. YouTube Data API has not been used
-- | -- | -- | --
youtube.0 | 2020-05-20 19:43:02.587 | error | (10150) youtube/v3/search - Status Code: 403 / Content: {"error":{"errors":[{"domain":"usageLimits","reason":"accessNotConfigured","message":"Access Not Configured. YouTube Data API has not been used
youtube.0 | 2020-05-20 19:43:02.579 | error | (10150) youtube/v3/channels - Status Code: 403 / Content: {"error":{"errors":[{"domain":"usageLimits","reason":"accessNotConfigured","message":"Access Not Configured. YouTube Data API has not been us
youtube.0 | 2020-05-20 19:43:02.572 | error | (10150) youtube/v3/channels - Status Code: 403 / Content: {"error":{"errors":[{"domain":"usageLimits","reason":"accessNotConfigured","message":"Access Not Configured. YouTube Data API has not been us


host.raspberrypi | 2020-05-20 19:43:00.023 | info | instance system.adapter.youtube.0 started with pid 10150
-- | -- | -- | --

Habe erst gedacht, die API hat keine Zugriffe mehr, da sind aber noch genug offen.

**Comment by klein0r** [comment]
Das klingt aber so, als ob der API-Key nicht für die YouTubeData API freigeschaltet ist

**Comment by Sledgehammer101** [comment]
Habe jetzt noch mal einen anderen API Schlüssel verwendet, selbes Problem. 
Hier noch mal alle Meldungen aus dem LOG, hatte vorhin vergessen auf debug zu ändern,sorry...


host.raspberrypi | 2020-05-20 20:21:19.555 | info | instance system.adapter.youtube.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
youtube.0 | 2020-05-20 20:21:19.003 | info | (14759) Terminated (NO_ERROR): Without reason
youtube.0 | 2020-05-20 20:21:18.431 | info | (14759) cleaned everything up...
youtube.0 | 2020-05-20 20:21:18.428 | debug | (14759) clearing kill timeout
host.raspberrypi | 2020-05-20 20:21:00.006 | warn | instance system.adapter.youtube.0 already running with pid 14759
youtube.0 | 2020-05-20 20:20:48.886 | error | (14759) youtube/v3/channels - Status Code: 403 / Content: {"error":{"errors":[{"domain":"usageLimits","reason":"accessNotConfigured","message":"Access Not Configured. YouTube Data API has not been use
youtube.0 | 2020-05-20 20:20:48.857 | debug | (14759) received data (403): {"error":{"errors":[{"domain":"usageLimits","reason":"accessNotConfigured","message":"Access Not Configured. YouTube Data API has not been used in project 518626521000 bef
youtube.0 | 2020-05-20 20:20:48.856 | debug | (14759) youtube/v3/channels - Request done - UCXge04HMY6nSzKMiiD2OBog
youtube.0 | 2020-05-20 20:20:48.849 | error | (14759) youtube/v3/search - Status Code: 403 / Content: {"error":{"errors":[{"domain":"usageLimits","reason":"accessNotConfigured","message":"Access Not Configured. YouTube Data API has not been used
youtube.0 | 2020-05-20 20:20:48.848 | debug | (14759) received data (403): {"error":{"errors":[{"domain":"usageLimits","reason":"accessNotConfigured","message":"Access Not Configured. YouTube Data API has not been used in project 518626521000 bef
youtube.0 | 2020-05-20 20:20:48.847 | debug | (14759) youtube/v3/search Request done
youtube.0 | 2020-05-20 20:20:48.398 | debug | (14759) youtube/v3/channels - Request init - UCXge04HMY6nSzKMiiD2OBog
youtube.0 | 2020-05-20 20:20:48.392 | debug | (14759) Found other channels, fetching data
youtube.0 | 2020-05-20 20:20:48.336 | info | (14759) starting. Version 0.0.11 in /opt/iobroker/node_modules/iobroker.youtube, node: v12.16.3
host.raspberrypi | 2020-05-20 20:20:44.364 | info | instance system.adapter.youtube.0 started with pid 14759
host.raspberrypi | 2020-05-20 20:20:44.337 | info | instance scheduled system.adapter.youtube.0 * * * * *

**Comment by Sledgehammer101** [comment]
So, ich konnte das Problem jetzt lösen. Scheinbar lag es wirklich am API Key, allerdings gibt es das Problem wohl öfter beim Zugriff auf Youtube Daten. 
Die Lösung war: Alle Projekte löschen und einen komplett neuen Key erstellen. Danach ging es ohne Probleme...
