### ISSUE TITLE
error regarding missing vis installation (no vis installed)

### ISSUE THREAD

**Issue by JoschaMiddendorf** [klein0r/ioBroker.youtube#16]
**Describe the bug**  
received error message in log:

host.TheBeast-ioBroker | 2020-07-29 14:18:27.121 | error | startInstance system.adapter.youtube.0: required adapter "vis" not found!

**To Reproduce**  
1. Restart Instance
2. View Log

**Expected behavior**  
No error message

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 0.0.11
 - JS-Controller version: 3.1.6
 - Node version: v12.18.2
 - Operating system: unRaid -> Docker: buanet/ioBroker

**Comment by JoschaMiddendorf** [comment]
Ich habe es mal mit einem Downgrade bis runter zu 0.0.6 versucht aber selbst da läuft der Adapter aktuell leider nicht mehr. Ich habe seit dem 24.7. keine neuen Werte mehr bekommen. Eventuell habe ich an dem Tag ein Update gemacht, kann es aber nicht sicher sagen.
Ein update auf 0.0.11 ist leider auch nicht mehr möglich:

```
$ ./iobroker upgrade youtube
ERROR: Required dependency "vis" not found on this host.
process exited with code 0
```

**Comment by klein0r** [comment]
Die Dependency habe ich in 0.0.12 rausgeworfen.
