### ISSUE TITLE
Adapter nicht mehr lauffähig unter JS-Controller 3.2.x

### ISSUE THREAD

**Issue by SBorg2014** [klein0r/ioBroker.youtube#23]
Der JSC ist zwar aktuell noch im Beta-Test, der YT-Adapter wird aber damit nach Veröffentlichung nicht mehr funktionieren:

(21985)  unhandled promise rejection: The id  "channels.HausAutomatisierungCom.video.0." is invalid. Ids are not  allowed to end in "."

(21985) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().

Nur schon ggf. als Vorabinfo.

Gruß
SBorg

**Comment by klein0r** [comment]
Danke, ich muss mal schauen warum dort überhaupt solche States angelegt werden sollen. Macht ja keinen Sinn 😄
